version: "1.0"

services:
  preprocessing:
    build: preprocessing
    ports:
      - 8004:8004
  modelserving:
    build: model-serving
    ports:
      - 8002:8002
  webapp:
    build: web-app
    ports:
      - 8003:8003
